export const REQUEST_CRYPTO_CURRENCIES_PENDING = 'REQUEST_CRYPTO_CURRENCIES_PENDING';
export const REQUEST_CRYPTO_CURRENCIES_SUCCESS = 'REQUEST_CRYPTO_CURRENCIES_SUCCESS';
export const REQUEST_CRYPTO_CURRENCIES_FAILED = 'REQUEST_CRYPTO_CURRENCIES_FAILED';